import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

const componentPath = "src/components/task-quick-edit.tsx";
const component = existsSync(componentPath) ? readFileSync(componentPath, "utf8") : "";
const detail = readFileSync("src/app/tasks/[taskId]/page.tsx", "utf8");
const scheduling = readFileSync("src/components/task-scheduling.tsx", "utf8");
const helpers = readFileSync("src/lib/task-quick-edit.ts", "utf8");
const assignmentOptions = readFileSync("src/app/api/tasks/[taskId]/assignment-options/route.ts", "utf8");
const projectDetail = readFileSync("src/app/projects/[projectId]/page.tsx", "utf8");

assert.match(detail, /<TaskQuickEdit[\s\S]*variant=["']facts["']/, "Detail must expose direct quick-edit facts.");
assert.match(component + helpers, /No date/);
assert.match(component + assignmentOptions, /Inbox/);
assert.match(scheduling, /<TaskQuickEdit[\s\S]*variant=["']trigger["']/, "Lists must use the unified quick-edit trigger.");
assert.match(component, /assignment-options/, "Destinations must use the lazy endpoint.");
assert.match(component, /nextView === ["']move["'][\s\S]{0,100}loadDestinations/, "Destination fetch must start only when Move opens.");
assert.match(component, /taskDatePresets/, "Quick edit must use the reviewed preset helper.");
assert.match(component, /Pick date/);
assert.match(component, /localStorage/);
assert.match(component, /operationToken/);
assert.match(component, /Couldn’t update task/);
assert.match(component, /Retry/);
assert.match(component, /Undo/);
assert.match(component, /6000/, "Undo must remain available for six seconds.");
assert.match(component, /role=["']dialog["']/);
assert.match(component, /aria-modal=["']true["']/);
assert.match(component, /aria-label=["']Quick edit task["']/);
assert.match(component, /min-h-11/, "Every action row must be at least 44px.");
assert.match(component, /break-words/);
assert.match(component, /\[overflow-wrap:anywhere\]/);
assert.match(component, /--app-bottom-clearance/);
assert.match(component, /safe-area-inset-bottom/);
assert.match(component, /motion-reduce:transition-none/);
assert.ok(!detail.includes("assignmentProjects"), "Detail must not eagerly query assignment options.");
assert.ok(!scheduling.includes("areaGroups"), "List quick edit must not receive eager Area options.");
assert.ok(!scheduling.includes("projects:"), "List quick edit must not receive eager Project options.");
assert.match(projectDetail, /<summary[^>]*min-w-0[^>]*[\s\S]{0,250}\[overflow-wrap:anywhere\]/, "Project Area disclosure must wrap unbroken hierarchy paths.");
