import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

const componentPath = "src/components/task-quick-edit.tsx";
const component = existsSync(componentPath) ? readFileSync(componentPath, "utf8") : "";
const detail = readFileSync("src/app/tasks/[taskId]/page.tsx", "utf8");
const scheduling = readFileSync("src/components/task-scheduling.tsx", "utf8");
const projectDetail = readFileSync("src/app/projects/[projectId]/page.tsx", "utf8");
const dock = readFileSync("src/components/app-dock.tsx", "utf8");
const globals = readFileSync("src/app/globals.css", "utf8");

assert.match(detail, /<TaskQuickEdit[\s\S]*variant=["']facts["']/, "Detail must expose direct quick-edit facts.");
assert.match(scheduling, /<TaskQuickEdit[\s\S]*variant=["']trigger["']/, "Lists must use the unified quick-edit trigger.");
assert.match(component, /6000/, "Undo must remain available for six seconds.");
assert.match(component, /role=["']dialog["']/);
assert.match(component, /aria-modal=["']true["']/);
assert.match(component, /aria-label=["']Quick edit task["']/);
assert.match(component, /min-h-11/, "Every action row must be at least 44px.");
assert.match(component, /break-words/);
assert.match(component, /\[overflow-wrap:anywhere\]/);
assert.match(component, /--app-dock-clearance/);
assert.match(dock, /--app-dock-clearance/);
assert.match(globals, /--app-dock-clearance/);
assert.match(globals, /8\.25rem/, "Dock clearance must reserve at least 132px before the safe area.");
assert.match(component, /locationTriggerRef/);
assert.match(component, /scheduleTriggerRef/);
assert.match(component, /data-dialog-initial/);
assert.match(component, /createPortal[\s\S]*TaskQuickEditStatus/);
assert.match(component, /motion-reduce:transition-none/);
assert.match(component, /variant\?:\s*["']facts["']\s*\|\s*["']trigger["']\s*\|\s*["']inbox["']/);
assert.match(component, /onMutation\?:\s*\(event:\s*TaskQuickEditMutationEvent\)/);
assert.match(component, /aria-label=["']Assign task["'][\s\S]{0,400}min-h-11[\s\S]{0,500}showDialog\(["']move["']/);
assert.match(component, /aria-label=["']Schedule task["'][\s\S]{0,400}min-h-11[\s\S]{0,500}showDialog\(["']quick["']/);
assert.match(component, /MutationPhase\s*=\s*["']optimistic["']\s*\|\s*["']committed["']\s*\|\s*["']rolled-back["']\s*\|\s*["']undo["']/);
assert.match(component, /mutationOwner\?:\s*TaskQuickEditMutationOwner/);
assert.match(component, /export function TaskQuickEditMutationStatusHost/);
assert.match(component, /variant === ["']inbox["'][\s\S]*mutationOwner/, "Inbox mutations must use an owner that can outlive the visual row.");
assert.ok(!detail.includes("assignmentProjects"), "Detail must not eagerly query assignment options.");
assert.ok(!scheduling.includes("areaGroups"), "List quick edit must not receive eager Area options.");
assert.ok(!scheduling.includes("projects:"), "List quick edit must not receive eager Project options.");
assert.match(projectDetail, /<summary[^>]*min-w-0[^>]*[\s\S]{0,250}\[overflow-wrap:anywhere\]/, "Project Area disclosure must wrap unbroken hierarchy paths.");
